# Generated by Django 5.0.2 on 2024-02-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
